web/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, json, jsonify
from .models import User, User_role_change_request, Equipment, Image, Request
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from sqlalchemy import and_, or_, not_
from flask_login import login_user, login_required, logout_user, current_user
from .sendpassword import generate_password
from .sendpassword import send_password
from flask_paginate import Pagination, get_page_parameter, get_page_args
from werkzeug.utils import secure_filename
import os
import requests
from datetime import datetime

auth = Blueprint('auth', __name__)


ACCESS = {
    'Guest': 0,
    'Research Assistant': 1,
    'Project PI':2,
    'Lab Manager':3,
    'Admin': 4
}

ROLE = {
    0: 'Guest',
    1: 'Research Assistant',
    2: 'Project PI',
    3: 'Lab Manager',
    4: 'Admin'
}

STATUS = {
    1: 'Available',
    2: 'Archived',
    3: 'Borrowed'
}


REQUEST_STATUS = {
    1: 'Pending',
    2: 'Approved',
    3: 'Rejected',
    4: 'Active',
    5: 'Finished'
}

@auth.context_processor
def base():
    number_of_user_role_change_request = User_role_change_request.query.count()
    return dict(ROLE=ROLE, 
                number_of_user_role_change_request = number_of_user_role_change_request,
                STATUS=STATUS,
                REQUEST_STATUS=REQUEST_STATUS
                )
    
@auth.route('/')
def home():    
    
    equipments = Equipment.query.filter(or_(Equipment.owner != 'Thanh',
                                            Equipment.location == 'JB305')).all() 
    nequips = len(equipments)
    # equipments = Equipment.query.filter(Equipment.owner.like('%{pattern}%'.format(pattern='h')) ).all() 
    return render_template("home.html", nequips =nequips , 
                                        list_of_equipments = list_of_equipments,
                                        equipments = equipments
                                        )

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('first_name')
        last_name = request.form.get('last_name')
        user_name = email[:email.index('@')]
        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        # elif ('@vinuni.edu.vn' not in email):
        #     flash('Email must be a vinuni email', category='error')
        elif (len(first_name) < 2):
            flash('First name must be at least 2 characters!', category='error')
        elif (len(last_name) < 2):
            flash('Last name must be at least 2 characters!', category='error')
        else:
            user_password =  generate_password()
            new_user = User(email, first_name, last_name, user_name, 0, 
                            generate_password_hash(user_password, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            mes = """We've emailed you a password. You should be receiving them shortly. 
            If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.
            See you soon!"""
            flash(mes, category='info')
            send_password(email, user_password, 'Welcome')
            return redirect(url_for('auth.login'))

    return render_template("sign_up.html")


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('auth.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html")


@auth.route('/passwordRecovery', methods=['GET', 'POST'])
def passwordRecovery():
    if request.method == 'POST':
        email = request.form.get('email')
        user = User.query.filter_by(email=email).first()
        if user:
            flash('Password recovery letter has been sent successfully', category='success')
            new_password =  generate_password()
            user.password = generate_password_hash(new_password, method='sha256')
            db.session.commit()
            send_password(email, new_password, 'Password recovery')
            return redirect(url_for('auth.login'))
        else:
            flash('Email does not exist.', category='error')
    return render_template('passwordRecovery.html')

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/profile/<username>')
def profile(username):
    user = User.query.filter_by(user_name=username).first_or_404() 
    return render_template('user_details.html', user=user)


@auth.route('/profile/<string:username>/edit-profile', methods=['GET', 'POST'])
@login_required
def editprofile(username):
    if current_user.user_name != username:
        return redirect(request.referrer)
    if (request.method == 'POST'):
        new_first_name = request.form.get('new_first_name')
        new_last_name = request.form.get('new_last_name')
        old_password = request.form.get('old_password')
        new_password = request.form.get('new_password')
        confirm_new_password = request.form.get('confirm_new_password')
        new_role = int(request.form.get('new_category'))
      
        changes = []
        if (len(new_first_name) > 0):
           changes.append(('change first name', new_first_name))
        if (len(new_last_name) > 0):
            changes.append(('change last name', new_last_name))
        if (len(old_password) > 0 or len(new_password) > 0 or len(confirm_new_password) > 0):
            changes.append(('change password', old_password, new_password, confirm_new_password))
        if (current_user.access != new_role):
            changes.append(('change category', new_role))
            
        check_valid = True

        for change in changes:
            if (change[0] == 'change first name' and len(new_first_name) < 2):
                flash('First name must be at least 2 characters', category='error')
                check_valid = False
                break
            if (change[0] == 'change last name' and len(new_last_name) < 2):
                flash('Last name must be at least 2 characters', category='error')
                check_valid = False
                break
            if (change[0] == 'change password'):
                if (check_password_hash(current_user.password, old_password) == False):
                    flash('Invalid current password', category='error')
                    check_valid = False
                    break
                if (len(new_password) < 6):
                    flash('New password must be  at least 6 characters')
                    check_valid = False
                    break
                if (new_password != confirm_new_password):
                    flash('Password and confirm password does not match', category='error')
                    check_valid = False
                    break
            if (change[0] == 'change category'):
                change_request = User_role_change_request.query.filter_by(new_role = new_role, user_id = current_user.id).first()
                if (change_request):
                    flash('You\'ve already requested this', category='error')
                    check_valid = False
                    break
            
        if (check_valid == False):
            return redirect(url_for('auth.editprofile', username=username))
        info_changed = False
        for change in changes:
            if (change[0] == 'change first name'):
                current_user.first_name = new_first_name
                info_changed = True
            if (change[0] == 'change last name'):
                current_user.last_name = new_last_name
                info_changed = True
            if (change[0] == 'change password'):
                current_user.password = generate_password_hash(new_password, method='sha256')
                info_changed = True
            if (change[0] == 'change category'):
                flash('Please wait for the admin to accpet your request', category='info')
                new_request = User_role_change_request(current_user.id, current_user.user_name, new_role)
                db.session.add(new_request)
        if (info_changed == True): 
            flash('Changes have been updated', category='success')
        db.session.commit()
        return redirect(url_for('auth.editprofile', username=username))
    return render_template('edit_profile.html', user=current_user)

@auth.route('/profile/<string:username>/personal-requests', methods=['GET', 'POST'])
def personal_requests(username):
    user = User.query.filter_by(user_name = username).first_or_404()
    
    
    request_list = Request.query.filter(Request.user_name == user.user_name)
    request_list = list(request_list)
    total = len(request_list)

    def condition(request):
        return request.date_requested
    request_list.sort(key = condition)
    
    request_list.reverse()
    
    def get_request(offset=0, per_page=10):
        return request_list[offset:offset+per_page]
    
        
    page, per_page, offset = get_page_args(page_parameter="page", per_page_parameter="per_page")
    
    pagination_requests = get_request(offset=offset, per_page=per_page)

web/templates/admin_edit_user_profile.html
{% extends "base.html" %} 
{% block title %}Edit Profile{% endblock %}
{% block csstyle %}
<link rel="stylesheet" href="{{ url_for('static', filename='admin_edit_user_profile_style.css') }}">
{% endblock %}
{% block content %}
    <div class="roundbox">
        <div class="user-name">
            {{user.user_name}}
        </div>
        <form method="POST">
            <div class="mb-3 row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Email</label>
                <div class="col-sm-10">
                    <input 
                        type="text" 
                        readonly 
                        class="form-control-plaintext" 
                        id="staticEmail" value={{user.email}}
                    >
                    </div>
                </div>
            
                <div class="mb-3 row">
                    <label for="new_first_name" class="col-sm-2 col-form-label">First name</label>
                    <div class="col-sm-10">
                        <input 
                            type="text" 
                            class="form-control" 
                            id="new_first_name"
                            name="new_first_name"
                            placeholder="{{user.first_name}}"
                        > 
                    </div>
                </div>

            <div class="mb-3 row">
                <label for="new_last_name" class="col-sm-2 col-form-label">Last name</label>
                <div class="col-sm-10">
                    <input 
                        type="text" 
                        class="form-control" 
                        id="new_last_name"
                        name="new_last_name"
                        placeholder="{{user.last_name}}"
                    > 
                </div>
            </div>
            
            <div class="mb-3 row">
                <label for="new_category" class="col-sm-2 col-form-label">Role</label>
                <div class="col-sm-10">    
                    <select class="form-select" id="new_category" name="new_category">
                        <option selected value="{{ current_user.access }}">{{ ROLE[user.access] }}</option>
                        {% if user.access != 0 %}
                            <option value="0">Guest</option>
                        {% endif %}    
                        {% if user.access != 1%}
                            <option value="1">Research Assistant</option>
                        {% endif %}
                        {% if user.access != 2 %} 
                            <option value="2">Project PI</option>
                        {% endif %}
                        {% if user.access != 3 and current_user.access >= 3 %}
                            <option value="3">Lab Manager</option>
                        {% endif %}
                        {% if user.access != 4 and current_user.access >= 4 %}
                            <option value="4">Admin</option>
                        {% endif %}
                    </select>
                </div>
            </div>
            <div style="text-align: center;">   
                <input class="submit" type="submit" value="Save changes">
            </div>
        </form>
    </div>
{% endblock %}

web/templates/assigned_equipments.html
{% extends "base.html" %}
{% block csstyle %}
<link rel="stylesheet" href="{{ url_for('static', filename='assigned_equipments.css') }}">
{% endblock %}

{% block title %}{{user.user_name}}{% endblock %}
{% block content %}
    <div class="roundbox">
        <div class="tabs">
            <h2 class="user-name">
                {{ user.user_name }}
            </h2>
            <span class="spacer"></span>
            <ul>
                <li class="tab-item">
                    <a href="/profile/{{user.user_name}}">
                        <i class="tab-icon fa fa-info-circle"></i>
                        About
                    </a>
                </li>
                <li class="tab-item">
                    <a href="/profile/{{user.user_name}}/assigned-equipments">
                        <i class="tab-icon fa fa-puzzle-piece"></i>
                        Assigned equipments
                    </a>
                </li>
                {% if current_user.is_authenticated and current_user == user %}
                <li class="tab-item">
                    <a href="{{ url_for('auth.editprofile', username=user.user_name) }}">
                        <i class="tab-icon fa fa-edit"></i>
                        Edit your profile
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
        <br>
        <table class="table caption-top">
            
            
        </table> 
    </div>
{% endblock %}

web/templates/borrowing_request.html
{% extends "base.html" %} 
{% block title %}Request List{% endblock %}
{% block csstyle %}
<link rel="stylesheet" href="{{ url_for('static', filename='borrowing_request_style.css') }}">
{% endblock %}
{% block content %} 
    <div class="table-responsive-sm">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">User</th>
                    <th scope="col">Equipment</th>
                    <th scope="col">Start date</th>
                    <th scope="col">End date</th>
                    <th scope="col">Status</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            {% for request in request_list %}
            <tr>    
                <td> <a href="/profile/{{request.user_name}}">{{request.user_name}}</a> </td>
                <td> <a href="/equipments/details/{{request.equip_name}}">{{request.equip_name}}</a> </td>
                <td>{{request.start_date}}</td>
                <td>{{request.end_date}}</td>
                {% if REQUEST_STATUS[request.status] == 'Rejected' %}
                <td  id="status-{{loop.index}}" class="status-rejected">Rejected</td>
                {% elif REQUEST_STATUS[request.status] == 'Approved' %}
                <td id="status-{{loop.index}}" class="status-approved">Approved</td>
                {% else %}
                <td id="status-{{loop.index}}" class="status-pending">Pending</td>
                {% endif %}

                <td>
                    <div style="display: flex; justify-content: start;">
                        <form action="{{ url_for('auth.accept_borrowing_request', id=request.id) }}" method="POST">
                            <input type="hidden" id="userChoice-{{loop.index}}" name="userChoice" value="empty">
                            <button type="submit" id="btn-approve-{{loop.index}}" class="btn btn-success btn-circle fa fa-check" onclick="confirm_action{{loop.index}}()"></button>
                        </form>
                        <form class="reject-btn" action="{{ url_for('auth.reject_borrowing_request', id=request.id) }}" method="POST">
                            <input type="hidden" id="userChoice2-{{loop.index}}" name="userChoice2" value="empty">
                            <button type="submit" id="btn-reject-{{loop.index}}" class="btn btn-danger btn-circle fa fa-times" onclick="confirm_action2{{loop.index}}()"></button>
                        </form>
                        <script>
                            function confirm_action{{loop.index}}(){
                                if (confirm('Are you sure?') == true)
                                document.getElementById("userChoice-{{loop.index}}").value = "True";
                                else{
                                    document.getElementById("userChoice-{{loop.index}}").value = "False"
                                    return 0;
                                }
                            }   
                            function confirm_action2{{loop.index}}(){
                                if (confirm('Are you sure?') == true)
                                document.getElementById("userChoice2-{{loop.index}}").value = "True";
                                else{
                                    document.getElementById("userChoice2-{{loop.index}}").value = "False"
                                    return 0;
                                }
                            }   
                        </script> 
                    </div>
                </td>
            </tr>
            {% endfor %} 
            <script>
                const total = {{total}}
                for (let i = 1; i <= total; i++){
                    if (document.getElementById("status-"+String(i)).className == 'status-approved'){
                        document.getElementById("btn-approve-"+String(i)).disabled = true;
                    }
                    if (document.getElementById("status-"+String(i)).className == 'status-rejected'){
                        document.getElementById("btn-reject-"+String(i)).disabled = true;
                    }
                }   
            </script>
        </table>
        {{ pagination.links }}
    </div>
    

{% endblock %}

web/templates/profile.html
{% extends "base.html" %}
{% block csstyle %}
<link rel="stylesheet" href="{{ url_for('static', filename='profile_style.css') }}">
{% endblock %}

{% block title %}{{user.user_name}}{% endblock %}

{% block content %}
    <div class="roundbox">
        <div class="tabs">
            <h2 class="user-name">
                {{ user.user_name }}
            </h2>
            <span class="spacer"></span>
            <ul>
                <li class="tab-item tab-item-details active">
                    <a href="/profile/{{user.user_name}}">
                        <i class="tab-icon fa fa-info-circle"></i>
                        About
                    </a>
                </li>
                <li class="tab-item tab-item-requests">
                    <a href="{{ url_for('auth.personal_requests', username=user.user_name) }}">
                        <i class="tab-icon fa fa-puzzle-piece"></i>
                        Requests
                    </a>
                </li>
                {% if current_user.is_authenticated and current_user == user %}
                
                <li class="tab-item tab-item-edit-profile">
                    <a href="{{ url_for('auth.editprofile', username=user.user_name) }}">
                        <i class="tab-icon fa fa-edit"></i>
                        Edit your profile
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>

        <br>    
        {% block profile_content %}
                            
        {% endblock %}   
    </div>
{% endblock %}

web/templates/user_list.html
{% extends "base.html" %} 
{% block title %}User List{% endblock %}
{% block csstyle %}
<link rel="stylesheet" href="{{ url_for('static', filename='user_list_style.css') }}">
{% endblock %}
{% block content %} 
    <div class="container-out">
        <div class="container-in">
        <div class="searchcontainer">
            <div class="search-engine">
                <p class="search-title">Search by username</p>
                <input
                    type="text"
                    name="input"
                    id="search-input"
                    autocomplete="off" 
                />
            </div>
            <div class="search-results-wrap">
                <ul id="search-results"></ul>   
            </div>
             
        </div>
        </div>
    </div>
    <script>
    
        function element(id) {
            return document.getElementById(id);
        }
        var ul = document.getElementById('search-results');
        var liSelected;
        var index = -1;
        let allSearchData = ""; 
        let names = {{ list_of_username | tojson }} 
        function getResults(){
            let search = element("search-input").value;
            allSearchData = ""; //clears data for each word typed
            index = 0;
            hideSearchResults();
            clearSearchResults(); 
            //starts searching from the second input
            if (search.length > 0) {
                let counter = 0; // counts to 10
                for (let x of names) {
                    if (counter < 15){
                        //checks for similarities
                        if (x.toLowerCase().includes(search.toLowerCase())) {
                            //populates the suggestion div
                            element("search-results").innerHTML +=
                                "<li class='search-item' id=\"\" onclick='displayData(\"" +
                                x +
                                "\")'>"+
                                x +
                                "</li>";

                            counter++;
                        }
                    }
                    if (x.toLowerCase().includes(search.toLowerCase()))
                        //saves all the realated names
                        allSearchData += "<p>" + x + "</p>";
                }
                displaySearchResults();        
            } 
        }
        //displays the suggestion div
        function displaySearchResults() {
            element("search-results").style.display = "list-item";
        }
        //clears the suggestion div
        function clearSearchResults() {
            element("search-results").innerHTML = "";
        }
        
        //hides the suggestion div
        function hideSearchResults() {
            element("search-results").style.display = "none"; 
        }
        //displays names when you click a suggestions
        function displayData(name) {
            window.location.href = '/users/search/' + name;
        }  
    
        //gets results after each input
        element("search-input").oninput = function() {
            getResults();
        };
        
        

        document.addEventListener('keydown', function(event) {
        var len = ul.getElementsByTagName('li').length - 1;
        if (event.which === 40) {
            index++;
            //down 
            if (liSelected) {
            removeClass(liSelected, 'selected');
            next = ul.getElementsByTagName('li')[index];
            if (typeof next !== undefined && index <= len) {
                liSelected = next;
                addClass(liSelected, 'selected');
                console.log(index);
                } else {
                index = 0;
    
                liSelected = ul.getElementsByTagName('li')[0];
                addClass(liSelected, 'selected');
                }
            } else {
                index = 0;
                liSelected = ul.getElementsByTagName('li')[0];
            }

        } else if (event.which === 38) {

            //up
            if (liSelected) {
            removeClass(liSelected, 'selected');
            index--;
            console.log(index);
            next = ul.getElementsByTagName('li')[index];
            if (typeof next !== undefined && index >= 0) {
                liSelected = next;
            } else {
                index = len;
                liSelected = ul.getElementsByTagName('li')[len];
            }
            addClass(liSelected, 'selected');
            } else {
            index = 0;
            liSelected = ul.getElementsByTagName('li')[len];
            addClass(liSelected, 'selected');
            }
            
        }
        }, false);

        function removeClass(el, className) {
        el.id = ''
        if (el.classList) {
            el.classList.remove(className);
        } else {
            el.className = el.className.replace(new RegExp('(^|\\b)' + className.split(' ').join('|') + '(\\b|$)', 'gi'), ' ');
        }
        };

        function addClass(el, className) {
        el.id = className
        if (el.classList) {
            el.classList.add(className);
        } else {
            el.className += ' ' + className;
            
        }
        };
        element("search-input").addEventListener("keyup", function(event) {
            if (event.keyCode === 13) {
                const name = document.getElementById('selected').textContent;
                window.location.href = '/users/search/' + name;
            }
        });
    </script>
    <table class="table">
        <thead>
            <th class="col-id">#</th>
            <th class="col">Username</th>
            <th class="col">First Name</th>
            <th class="col">Last Name</th>
            <th class="col">Role</th>
            {% if current_user.is_authenticated and current_user.access >= 3 %}
                <th class="col">Action</th>
            {% endif %}
        </thead>
        <tbody>
                   
            {% for user in users %}
                <tr id="user-{{user.user_name}}" class="user-details">
                    <td>{{ user.id }}</td>
                    <td>
                        <a href="{{ url_for('auth.profile', username=user.user_name) }}">{{ user.user_name }}</a>
                    </td>
                    <td>{{ user.first_name }}</td>
                    <td>{{ user.last_name }}</td>
                    <td>{{ ROLE[user.access] }}</td>
                    {% if current_user.is_authenticated and current_user.access >= 3 %}
                    <td>
                        <div style="display: flex;">
                            <a href="{{ url_for('auth.admin_edit_user_profile', username=user.user_name) }}" class="far fa-edit" style="color:black;text-decoration: none;"></a>
                            <form action="{{ url_for('auth.admin_delete_user', id=user.id) }}" method="POST">
                                <input type="hidden" id="userChoice-{{loop.index}}" name="userChoice" value="empty">
                                <button type="submit" class="btn far fa-trash-alt" onclick="confirm_action{{loop.index}}()"></button>
                            </form>
                            <script>
                                function confirm_action{{loop.index}}(){
                                    if (confirm('Are you sure?') == true)
                                        document.getElementById("userChoice-{{loop.index}}").value = "True";
                                    else{
                                        document.getElementById("userChoice-{{loop.index}}").value = "False"
                                        return 0;
                                    }
                                }   
                            </script> 
                        </div>
                    </td>
                    {% endif %}
                </tr>
            {% endfor %}  
        </tbody>
    </table>
    {{ pagination.links }} 
{% endblock %}

web/templates/user_list_show_result.html
{% extends "base.html" %} 
{% block title %}User List{% endblock %}
{% block csstyle %}
<link rel="stylesheet" href="{{ url_for('static', filename='user_list_style.css') }}">
{% endblock %}
{% block content %} 
    <div class="above" style="margin-bottom: 10px;">
        <a href="/" style="text-decoration: none; color: black;">Home</a>
        /
        <a href="/users" style="text-decoration: none; color: black;">Users</a>
        /
        Search
    </div>
    

    <table class="table ">
        <thead>
            <th class="col-id ">#</th>
            <th class="col">Username</th>
            <th class="col">First Name</th>
            <th class="col">Last Name</th>
            <th class="col">Role</th>
            {% if current_user.is_authenticated and current_user.access >= 3 %}
                <th class="col">Action</th>
            {% endif %}
        </thead>
        <tbody>
                   
            {% for user in users %}
                <tr id="user-{{user.user_name}}" class="user-details">
                    <td>{{ user.id }}</td>
                    <td>
                        <a href="{{ url_for('auth.profile', username=user.user_name) }}">{{ user.user_name }}</a>
                    </td>
                    <td>{{ user.first_name }}</td>
                    <td>{{ user.last_name }}</td>
                    <td>{{ ROLE[user.access] }}</td>
                    {% if current_user.is_authenticated and current_user.access >= 3 %}
                    <td>
                        <div style="display: flex;">
                            <a href="{{ url_for('auth.admin_edit_user_profile', username=user.user_name) }}" class="far fa-edit" style="color:black;text-decoration: none;"></a>
                            <form action="{{ url_for('auth.admin_delete_user', id=user.id) }}" method="POST">
                                <input type="hidden" id="userChoice-{{loop.index}}" name="userChoice" value="empty">
                                <button type="submit" class="btn far fa-trash-alt" onclick="confirm_action{{loop.index}}()"></button>
                            </form>
                            <script>
                                function confirm_action{{loop.index}}(){
                                    if (confirm('Are you sure?') == true)
                                        document.getElementById("userChoice-{{loop.index}}").value = "True";
                                    else{
                                        document.getElementById("userChoice-{{loop.index}}").value = "False"
                                        return 0;
                                    }
                                }   
                            </script> 
                        </div>
                    </td>
                    {% endif %}
                </tr>
            {% endfor %}  
        </tbody>
    </table>
    {{ pagination.links }}
{% endblock %}